export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/onboard/index',
    'pages/register/index',
    'pages/pending/index',
    'pages/bind/index',
    'pages/index/index',
    'pages/cart/index',
    'pages/like/index',
    'pages/profile/index',
    'pages/orderList/index',
    'pages/orderDetail/index',
    'pages/refunderList/index',
    'pages/refunderDetail/index',
    'pages/refunderApply/index',
    'pages/updateProfile/index',
    'pages/unbound/index',
    'pages/confirmPay/index',
    'pages/address/index',
    'pages/addressEdit/index',
    'pages/payment/index',
  ],
  tabBar: {
    custom: true,
    color: '#efefef',
    selectedColor: '#edcb43',
    backgroundColor: '#1a1212',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
      },
      {
        pagePath: 'pages/cart/index',
        text: '购物车',
      },
      {
        pagePath: 'pages/like/index',
        text: '我的收藏',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ff640c',
    navigationBarTitleText: '有善商户',
    navigationBarTextStyle: 'white',
    backgroundColor: '#cac5c5',
    backgroundColorTop: '#ff640c',
    backgroundColorBottom: '#cac5c5',
  },
})
